config/routes.rb
Rails.application.routes.draw do

  resources :libros
  resources :home
  resources :autores

  root to: 'libros#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autor.rb
class Autor < ApplicationRecord
  has_many :libros
end

app/models/libro.rb
class Libro < ApplicationRecord
#	has_one_attached :image_url
  belongs_to :autor

  validates :titulo, :precio, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/autores_controller.rb
class AutoresController < ApplicationController
  def index
    @autores = Autor.all.order("id")
  end

  def new
    @autor = Autor.new
  end

  def show
    @autor = Autor.find(params[:id])
  end

  def create
    @autor = Autor.new(autor_params)
    if @autor.save
      redirect_to @autor
    else
      render :new
    end
  end

  def update
    @autor = Autor.find(params[:id])
    if @autor.update(autor_params)
      redirect_to autores_path #@autor
    else
      render :edit
    end
  end

  def edit
    @autor = Autor.find(params[:id])
  end

  def destroy
    autor = Autor.find(params[:id])
    autor.destroy

    redirect_to autores_path, notice: "The author was deleted successfully."
  end
# For security
  private
  def autor_params
    params.require(:autor).permit(:nombre, :apellido_paterno, :apellido_materno)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  def index
    @libros = Libro.all.order("id")
    @autores = Autor.all
  end

  def new
    @libro = Libro.new
    puts "Hello new, geeks"
  end

  def create
    @libro = Libro.create(libro_params)
    if @libro.save
      redirect_to @libro #libros_path
    else
      render :new
    end
  end

  def show
    @libro = Libro.find(params[:id])
  end

  def edit
    @libro = Libro.find(params[:id])
  end

  def update
    @libro = Libro.find(params[:id])
    puts "Hello, I'am here!"
    if @libro.update(libro_params)
      redirect_to libros_path
    else
      render :edit
    end
  end

  def destroy
    libro = Libro.find(params[:id])
    libro.destroy

    flash[:notice] = "The book was deleted successfully."
    redirect_to libros_path
  end

private
  def libro_params
    params.require(:libro).permit(:titulo, :precio, :descripcion, :fecha_publicacion, :autor_id, :image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autores_helper.rb
module AutoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/autores/edit.html.erb
<h1>Autores edit</h1>
<%= form_for @autor do |f| %>
  <div >
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>
  <div>
    <%= f.label :apellido_paterno %>
    <%= f.text_field :apellido_paterno %>
  </div>
  <div>
    <%= f.label :apellido_materno %>
    <%= f.text_field :apellido_materno %>
  </div>

  <div>
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/autores/index.html.erb
<div class="container">
  <h1>Autores#index</h1>
  <%= link_to "New Author", new_autor_path %>
  <table border="1">
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Apellido Paterno</th>
      <th>Apellido Materno</th>
      <th style="text-align: center">Acciones</th>
    </tr>
    <tbody>
      <% @autores.each do |a|%>
      <tr>
        <th><%= a.id %></th>
        <td><%= a.nombre %></td>
        <td><%= a.apellido_paterno %></td>
        <td><%= a.apellido_materno %></td>
        <td>
          <%= link_to "Show" %>
          <%= link_to "Edit", edit_autor_path(a) %>
          <%= link_to "Delete"%>
      </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/autores/new.html.erb
<h1>Autores --new</h1>
<%= form_for @autor do |f| %>
  <div >
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>
  <div>
    <%= f.label :apellido_paterno %>
    <%= f.text_field :apellido_paterno %>
  </div>
  <div>
    <%= f.label :apellido_materno %>
    <%= f.text_field :apellido_materno %>
  </div>

  <div>
    <%= f.submit "Save"  %>
  </div>
<% end %>

app/views/autores/show.html.erb
<h1>Autores#show</h1>
<p>Find me in app/views/autores/show.html.erb</p>

app/views/home/index.html.erb
<div class="container">
<h1>Everything is up to you</h1>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" style="height: 100vh">
      <img class="d-block w-100" src="assets/girl.jpg" alt="First slide" >
      <h5>Read</h5>
      <p>helo</p>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/girl2.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/girl3.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libreria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link rel="stylesheet" href="/assets/estilos.css">
<!-- Archivos de Bootstrap v4.3 -->
<link rel="stylesheet" href="/css/bootstrap.min.css">
<link rel="stylesheet" href="/css/bootstrap.min.js">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#">Books</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= home_index_path %>">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= libros_path%>">Libros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= autores_path %>">Autores</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>

    <% flash.each do |name, msg|  -%>
    <%= content_tag :div, msg, class: mame %>
    <% end -%>

    <%= yield %>


  </body>
</html>

app/views/libros/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div class="card mt-5">



     <div class="card-header font-weight-bold" style="text-align: center"><%= title %></div>
    
   <%= form_for @libro do |f| %>
 <div class="card-body">
<% if @libro.errors.any? %>
  <div id="card border-0">
    <p>This form contains <%= pluralize(@libro.errors.count, "error") %>:</p>
    <ul>
    <% @libro.errors.full_messages.each do |msg| %>
      <li class="text-danger"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="form-group">
     <%= f.label :titulo %> 
      <%= f.text_field :titulo, class: "form-control", autofocus: true %> 
    </div>
    <div class="form-control">
      <%= f.label :image_url %>
      <%= f.file_field :image_url %>
    </div>

    <div class="form-group">
      <%= f.label :precio %>
        <%= f.text_field :precio, class: "form-control" %> 
        </div>
        <div class="form-group">
      <%= f.label "Autor" %>
        <%= f.select(:autor_id, Autor.all.collect{|a| [a.nombre, a.id]}, {prompt: "Seleccione autor"}, {class: 'form-control'}) %>
        </div>
        <div class="form-group">
       <%= f.label :descripcion %>
          <%= f.text_area :descripcion, rows: 4, class: "form-control" %>
          </div>
          <div class="form-group">
      <%= f.label :fecha_publicacion %> 
        <%= f.date_field :fecha_publicacion, class: "form-control" %> 
      </div>
      </div>

        <div class="card-footer text-right">
          <%= link_to "Cancel", libros_path, class: "btn btn-danger" %>
          <%= f.submit "Save" , class: "btn btn-primary" %>
        </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/libros/edit.html.erb
<%= render "form", title: "Editar Libro" %>

app/views/libros/index.html.erb
<div class="container">

<h1>Libros</h1>
<%= link_to "Nuevo Libro", new_libro_path %>
<table border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th>Título</th>
      <th>Imagen</th>
      <th>Autor</th>
      <th>Descripción</th>
      <th>Fecha de Publicación</th>
      <th style="text-align: center"> Acciones </th>
    </tr>
  </thead>
  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.id %></td>
        <td><%= libro.titulo %></td>
        
        <% autor = libro.autor.blank?  ? "--Sin autor--" : libro.autor.nombre.to_s    %>
        <td><%= autor %></td>
        <td><%= libro.precio %></td>
        <td><%= libro.fecha_publicacion %></td>
        <td>
          <%= link_to "Mostrar", libro %>
          <%= link_to "Editar", edit_libro_path(libro) %>
          <%= link_to "Eliminar", libro, method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/libros/new.html.erb
<%= render "form", title: "Agregar Libro" %>

app/views/libros/show.html.erb
<h1>Detalles del Libro</h1>
<div>Nombre: <%= @libro.titulo %></div>